apiVersion: v1
kind: Service
metadata:
  name: trivago-app
  labels:
    app: trivago-app
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: trivago-app
    tier: trivago-app
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trivago-app
  labels:
    app: trivago-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: trivago-app
        tier: trivago-app
    spec:
      containers:
      - image: 127.0.0.1:30400/trivago-app:$BUILD_NUMBER
        name: trivago-app
        ports:
        - containerPort: 8080
          name: trivago-app